### ISSUE TITLE
Web server

### ISSUE THREAD

**Issue by serhii-londar** [festrs/DotaComp#8]
Whyserver isn't working? Can you share your server?

**Comment by festrs** [comment]
Yes I can share, the web server is working. See this git https://github.com/festrs/DotaComp-Service

and this git for the worker https://github.com/festrs/DotaComp-Worker

LiveGamesURL = "https://dotacomp-service.herokuapp.com/api/livegames/true"
UpCommingGamesURL = "https://dotacomp-service.herokuapp.com/api/upcominggames"
EndedGamesURL = "https://dotacomp-service.herokuapp.com/api/endedgames"

It's free to use, you can make requests there, feel free to ask any questions.

**Comment by serhii-londar** [comment]
It's very nice!!! Thank you!
How do you get upcomming mathes?
